######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 28 07:19:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
SOURCES += main.cpp mainWindow.cpp
RESOURCES += qsouce.qrc
